version: "3.7"
services:
  ai-service:
    image: congzhao0294/ai-service:latest  
    container_name: 'ai-service'
    restart: always
    ports:
      - "5001:5001"  
    env_file:
      - .env  # Load environment variables from .env file
    networks:
      - backend_services  

networks:
  backend_services:
    driver: bridge  